name: FiveM Server Deployment

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Update FiveM server on OVH VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          # Connect to the server and execute commands
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p "${{ secrets.VPS_SSH_PORT }}" "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_HOST }}" << 'EOF'
          cd /home/fresh/artefact/txData/QBCoreFramework_C683CD.base
          git pull origin cicd
          ./restart.sh
          EOF
